import React, { useState } from 'react';
import './Experiences.css';

const Experiences = () => {
  const [activeTab, setActiveTab] = useState('industry');

  const industryData = [
    {
      title: "Software Engineering Intern",
      company: "Medtronic",
      duration: "Jun 2025 - Present",
      location: "Boston, MA",
      description: [
        "I built a MATLAB/Simulink software testing framework for Hugo RAS system, enabling hardware-free system testing and reducing validation time. I also designed a Unity VR simulation with movement tracking, logging of 8-DOF data, and playback functionality for a formative user study."
      ],
      technologies: ["Unity", "C#", "MATLAB", "Simulink", "Docker", "DDS", "Git"],
      logo: "/logos/medtronic.png"
    },
    {
      title: "Software Applications Engineering Intern",
      company: "Triple Ring Technologies",
      duration: "Jun 2024 - Aug 2025",
      location: "Newark, CA",
      description: [
        "I utilized C# and XAML to develop GUI applications for 2 diagnostic medical devices intended for market release. I additionally developed black box and code inspection test cases for traceability and acceleration of software verification."
      ],
      technologies: ["C#", "XAML", "Figma", ".NET", "Git"],
      logo: "/logos/triplering.png"
    },
    {
      title: "DxD HealthTech Intern",
      company: "Stanford Biodesign",
      duration: "Jul 2024",
      location: "Mountain View, CA",
      description: [
        "I was selected to attend Stanford Biodesign’s rigorous 2024 DxD Healthtech Workshop, engaging with industry leaders and other college interns from underrepresented groups in health technology. I explored new innovation in medtech and participated in needs-driven Biodesign innovation process."
      ],
      technologies: ["Human-centered design", "need-finding", "problem framing and validation"],
      logo: "/logos/dxd.png",
    },
    {
      title: "Data Analytics Intern",
      company: "National Institute of Standards and Technology",
      duration: "Aug 2023 - May 2024",
      location: "Gaithersburg, MD",
      description: [
        "I utilized R  to curate, analyze, and visualize large-scale forensic DNA profiling data for publication. I programmed a novel R pipeline that increased the speed of labeling and differentiation of allelic and stutter peaks."
      ],
      technologies: ["R", "STRmix", "ggplot2", "Plotly"],
      logo: "/logos/nist.png",
      publications: [
        {
          authors: "Riman, S., Bright, J., Huffman, K., Moreno, L., Liu, S., Sathya, A., Vallone, P.",
          title: "A collaborative study on the precision of the Markov chain Monte Carlo algorithms used for DNA profile interpretation.",
          journal: "Forensic Science International: Genetics",
          year: "2024",
          doi: "https://doi.org/10.1016/j.fsigen.2024.103088"
        }
      ]
    }
  ];

  const researchData = [
    {
      title: "Department of Biomedical Engineering Ahn Lab",
      company: "Johns Hopkins University",
      duration: "Jul 2021 - Present",
      location: "Baltimore, MD",
      description: [
        "Leveraged R and Python to create over 40 data visualizations for analysis and contributed to 2 publications on whole-exome and duplex sequencing of primary and recurrent glioblastoma tumors. Utilized GDC API, GeneCards API, and Python to create pipeline to annotate mutations with TCGA data and clinical significance. Produced 3 TCGA computational tutorials and taught to 150 students in biochemistry course (CTEI Instructional Enhancement Grant)."
      ],
      technologies: ["R", "Python", "TCGA", "OpenCRAVAT", "GDC", "SigmaPlot"],
      logo: "/logos/hopkinsbme.png",
      mentor: "Dr. Eun Hyun Ahn"
    },
    {
      title: "Advanced Robotics and Computationally Augmented Environments Lab",
      company: "Johns Hopkins University LCSR",
      duration: "Sep 2023 - May 2024",
      location: "Baltimore, MD",
      description: [
        "Developed a programming interface using Unity, C#, and Blender to position a dynamic 3D model of the Loop-X mobile imaging robot along 6 coordinates. Reduced integration time of 3D digital twin Operating Room with virtual reality by 15%, enhancing surgical training."
      ],
      technologies: ["Unity", "C#", "Blender", "Plotly"],
      logo: "/logos/lcsr.jpeg",
      mentor: "Dr. Mathias Unberath"
    },
    {
      title: "Bioinformatics and Computational Biology Lab",
      company: "Johns Hopkins University",
      duration: "Jun 2023 - Dec 2024",
      location: "Baltimore, MD",
      description: [
        "Employed Biopython and Snakemake in a Unix environment to analyze 177 barcode sequences generated by new multiplex detection of protein-protein interaction technology. Optimized mapping of merged and paired-end reads to reference genome, reducing processing time by 20%."
      ],
      technologies: ["Biopython", "Snakemake", "Bowtie 2", "Linux", "Unix"],
      logo: "/logos/hopkinsbme.png",
      mentor: "Dr. Joel Bader"
    },
    {
        title: "NJIT NSF REU: Optics and Photonics",
        company: "New Jersey Institute of Technology",
        duration: "May 2022 - July 2022",
        location: "Newark, NJ",
        description: [
          "Executed nanoparticle tracking analysis of 8 polystyrene particles to identify optimal blood circulation for targeted drug delivery. Presented findings on improving circulation of particles by 45% at NJIT Undergraduate Research and Innovation Symposium."
        ],
        technologies: ["Nanosight", "Excel", "Zetasizer"],
        logo: "/logos/njit.png",
        mentor: "Dr. Kathleen McEnnis",
        publications: [
          {
            authors: "Ruiz, A.L., Xiao, M., Sathya, A., Piccininni, N., Liu, G., Siddiq, N., Chen, H., & McEnnis, K.",
            title: "Influence of particle z-potential and experimental procedure on protein corona formation and multicomponent aggregation.",
            journal: "AIChE Journal",
            year: "2023",
            volume: "69(12)",
            doi: "https://doi.org/10.1002/aic.18237"
          }
        ]
    }
  ];

  const renderExperiences = (experiences) => {
    return experiences.map((exp, index) => (
      <div key={index} className="experience-item">
        <div className="experience-bar">
          <div className="experience-bar-content">
            <div className="experience-logo-circle">
              <img src={exp.logo} alt={exp.company + ' logo'} />
            </div>
            <span className="experience-company">{exp.company}</span>
          </div>
        </div>
        <div className="experience-header-text">
          <div className="experience-title">
            <h3>{exp.title}</h3>
          </div>
          <div className="experience-meta-row">
            <span className="location">{exp.location}</span>
            <span className="duration">{exp.duration}</span>
          </div>
        </div>
        {exp.mentor && (
          <div className="mentor">
            Mentor: {exp.mentor}
          </div>
        )}
        <div className="experience-description">
          {exp.description.map((desc, idx) => (
            <p key={idx}>{desc}</p>
          ))}
        </div>
        <div className="technologies">
          Skills: {exp.technologies.join(', ')}
        </div>
        {exp.publications && exp.publications.length > 0 && (
          <div className="publications">
            {exp.publications.map((pub, idx) => (
              <div key={idx} className="publication">
                <span className="publication-label">Publication: </span>
                <a href={pub.doi || 'https://placeholder.url'} target="_blank" rel="noopener noreferrer" className="publication-title">
                  {pub.title}
                </a>
              </div>
            ))}
          </div>
        )}
      </div>
    ));
  };

  return (
    <div className="experiences">
      <div className="container">
        <h2 className="section-title">Experience</h2>
        
        <div className="experience-tabs">
          <button 
            className={`tab-button ${activeTab === 'industry' ? 'active' : ''}`}
            onClick={() => setActiveTab('industry')}
            data-tab="industry"
          >
            Industry
          </button>
          <button 
            className={`tab-button ${activeTab === 'research' ? 'active' : ''}`}
            onClick={() => setActiveTab('research')}
            data-tab="research"
          >
            Research
          </button>
        </div>

        <div className="experiences-content">
          {activeTab === 'industry' && renderExperiences(industryData)}
          {activeTab === 'research' && renderExperiences(researchData)}
        </div>
      </div>
    </div>
  );
};

export default Experiences; 